- name: Deploy WAR file to Tomcat
  hosts: tomcat
  become: yes

  vars:
    tomcat_version: 10.1.52
    tomcat_install_dir: /opt/tomcat
    tomcat_webapps: /opt/tomcat/apache-tomcat-{{ tomcat_version }}/webapps

  tasks:
    - name: Copy WAR file to Tomcat webapps
      copy:
        src: "{{ war_file }}"
        dest: "{{ tomcat_webapps }}/votingapp.war"
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
